#include "./ArbitraryDegreeRational_test.hpp"
#include "./Rational_test.cpp"
#include "./rails/PolynomialTrain_test.cpp"
#include "./rails/RationalTrain_test.cpp"
#include "./rails/PolynomialRailyard_test.hpp"
#include "./Polynomial_test.hpp"
#include "./ArbitraryDegreePolynomial_test.hpp"
