#include "./ArbitraryDegreeRational_test.hpp"
#include "./Rational_test.hpp"
#include "./rails/PolynomialRailyard_algebraic_test.hpp"
#include "./rails/PolynomialRailyard_composition_test.cpp"
#include "./rails/PolynomialTrain_algebraic_test.cpp"
#include "./rails/RationalTrain_test.cpp"
#include "./Polynomial_test.hpp"
#include "./ArbitraryDegreePolynomial_test.hpp"
