#include "./Stratum_StratumTypes_test.cpp"
#include "./StratumMassPoolStore_test.cpp"
#include "./Stratum_operators_test.cpp"
#include "./StratumMassPool_operators_test.cpp"
#include "./StratumStore_test.cpp"
