#include "./CompletedSolid_to_string_test.cpp"
#include "./PartlyKnownSolid_operators_test.hpp"
#include "./PartlyKnownSolid_test.cpp"
#include "./PartlyKnownSolid_to_CompletedSolid_test.cpp"
#include "./PartlyKnownSolid_to_string_test.cpp"
