#pragma once

// std libraries
#include <string>

// in-house libraries
#include <unit/si.hpp>

#include <model/compound/ids.hpp>
#include <model/compound/table/FullTable.hpp>

namespace compound {

    namespace polymorphs {

        enum enumeration{

            water_ice_1h,
            water_ice_1c,
            water_ice_2,
            water_ice_3,
            water_ice_4,
            water_ice_5,
            water_ice_6,
            water_ice_7,
            water_ice_8,
            water_ice_9,
            water_ice_10,
            water_ice_11h,
            water_ice_11o,
            water_ice_12,
            water_ice_13,
            water_ice_14,
            water_ice_15,
            water_ice_16,
            water_ice_17,
            water_ice_18,
            water_ice_19,
            nitrogen_ice_beta,
            nitrogen_ice_alpha,
            nitrogen_ice_gamma,
            oxygen_ice_gamma,
            oxygen_ice_beta,
            oxygen_ice_alpha,
            carbon_dioxide_ice,
            methane_ice_alpha,
            methane_ice_beta,
            argon_ice,
            helium_ice,
            hydrogen_ice,
            ammonia_ice,
            ozone_ice,
            nitrous_oxide_ice,
            sulfur_dioxide_ice,
            nitric_oxide_ice,
            carbon_monoxide_ice_beta,
            carbon_monoxide_ice_alpha,
            ethane_ice,
            hydrogen_cyanide_ice,
            ethanol_ice,
            formaldehyde_ice,
            formic_acid_ice,
            perflouromethane_ice,
            benzene_ice,
            pyrimidine_ice,
            quartz_alpha,
            quartz_beta,
            crystoballite_alpha,
            crystoballite_beta,
            halite,
            corundum,
            apatite,
            graphite,
            diamond,
            calcite,
            aragonite,
            orthoclase,
            andesine,
            augite,
            forsterite,
            goethite,
            pyrite,
            hematite,
            gold,
            silver,
            copper,
            magnetite,
            chalcocite_alpha,
            chalcocite_beta,
            chalcopyrite

        };

        int count = 73;
    };

    table::FullTable<std::string> polymorph_name {
        /*water_ice_1h*/              "water ice 1h",
        /*water_ice_1c*/              "water ice 1c",
        /*water_ice_2*/               "water ice 2",
        /*water_ice_3*/               "water ice 3",
        /*water_ice_4*/               "water ice 4",
        /*water_ice_5*/               "water ice 5",
        /*water_ice_6*/               "water ice 6",
        /*water_ice_7*/               "water ice 7",
        /*water_ice_8*/               "water ice 8",
        /*water_ice_9*/               "water ice 9",
        /*water_ice_10*/              "water ice 10",
        /*water_ice_11h*/             "water ice 11h",
        /*water_ice_11o*/             "water ice 11o",
        /*water_ice_12*/              "water ice 12",
        /*water_ice_13*/              "water ice 13",
        /*water_ice_14*/              "water ice 14",
        /*water_ice_15*/              "water ice 15",
        /*water_ice_16*/              "water ice 16",
        /*water_ice_17*/              "water ice 17",
        /*water_ice_18*/              "water ice 18",
        /*water_ice_19*/              "water ice 19",
        /*nitrogen_ice_beta*/         "nitrogen ice beta",
        /*nitrogen_ice_alpha*/        "nitrogen ice alpha",
        /*nitrogen_ice_gamma*/        "nitrogen ice gamma",
        /*oxygen_ice_gamma*/          "oxygen ice gamma",
        /*oxygen_ice_beta*/           "oxygen ice beta",
        /*oxygen_ice_alpha*/          "oxygen ice alpha",
        /*carbon_dioxide_ice*/        "carbon dioxide ice",
        /*methane_ice_alpha*/         "methane ice alpha",
        /*methane_ice_beta*/          "methane ice beta",
        /*argon_ice*/                 "argon ice",
        /*helium_ice*/                "helium ice",
        /*hydrogen_ice*/              "hydrogen ice",
        /*ammonia_ice*/               "ammonia ice",
        /*ozone_ice*/                 "ozone ice",
        /*nitrous_oxide_ice*/         "nitrous oxide ice",
        /*sulfur_dioxide_ice*/        "sulfur dioxide ice",
        /*nitric_oxide_ice*/          "nitric oxide ice",
        /*carbon_monoxide_ice_beta*/  "carbon monoxide ice beta",
        /*carbon_monoxide_ice_alpha*/ "carbon monoxide ice alpha",
        /*ethane_ice*/                "ethane ice",
        /*hydrogen_cyanide_ice*/      "hydrogen cyanide ice",
        /*ethanol_ice*/               "ethanol ice",
        /*formaldehyde_ice*/          "formaldehyde ice",
        /*formic_acid_ice*/           "formic acid ice",
        /*perflouromethane_ice*/      "perflouromethane ice",
        /*benzene_ice*/               "benzene ice",
        /*pyrimidine_ice*/            "pyrimidine ice",
        /*quartz_alpha*/              "quartz alpha",
        /*quartz_beta*/               "quartz beta",
        /*crystoballite_alpha*/       "crystoballite alpha",
        /*crystoballite_beta*/        "crystoballite beta",
        /*halite*/                    "halite",
        /*corundum*/                  "corundum",
        /*apatite*/                   "apatite",
        /*graphite*/                  "graphite",
        /*diamond*/                   "diamond",
        /*calcite*/                   "calcite",
        /*aragonite*/                 "aragonite",
        /*orthoclase*/                "orthoclase",
        /*andesine*/                  "andesine",
        /*augite*/                    "augite",
        /*forsterite*/                "forsterite",
        /*goethite*/                  "goethite",
        /*pyrite*/                    "pyrite",
        /*hematite*/                  "hematite",
        /*gold*/                      "gold",
        /*silver*/                    "silver",
        /*copper*/                    "copper",
        /*magnetite*/                 "magnetite",
        /*chalcocite_alpha*/          "chalcocite alpha",
        /*chalcocite_beta*/           "chalcocite beta",
        /*chalcopyrite*/              "chalcopyrite"
    };

    table::FullTable<int> polymorph_similarity {
        /*water_ice_1h*/              polymorphs::water_ice_1h,
        /*water_ice_1c*/              polymorphs::water_ice_1h,
        /*water_ice_2*/               polymorphs::water_ice_1h,
        /*water_ice_3*/               polymorphs::water_ice_1h,
        /*water_ice_4*/               polymorphs::water_ice_1h,
        /*water_ice_5*/               polymorphs::water_ice_1h,
        /*water_ice_6*/               polymorphs::water_ice_1h,
        /*water_ice_7*/               polymorphs::water_ice_1h,
        /*water_ice_8*/               polymorphs::water_ice_1h,
        /*water_ice_9*/               polymorphs::water_ice_1h,
        /*water_ice_10*/              polymorphs::water_ice_1h,
        /*water_ice_11h*/             polymorphs::water_ice_1h,
        /*water_ice_11o*/             polymorphs::water_ice_1h,
        /*water_ice_12*/              polymorphs::water_ice_1h,
        /*water_ice_13*/              polymorphs::water_ice_1h,
        /*water_ice_14*/              polymorphs::water_ice_1h,
        /*water_ice_15*/              polymorphs::water_ice_1h,
        /*water_ice_16*/              polymorphs::water_ice_1h,
        /*water_ice_17*/              polymorphs::water_ice_1h,
        /*water_ice_18*/              polymorphs::water_ice_1h,
        /*water_ice_19*/              polymorphs::water_ice_1h,
        /*nitrogen_ice_beta*/         polymorphs::nitrogen_ice_beta,
        /*nitrogen_ice_alpha*/        polymorphs::nitrogen_ice_beta,
        /*nitrogen_ice_gamma*/        polymorphs::nitrogen_ice_beta,
        /*oxygen_ice_gamma*/          polymorphs::oxygen_ice_gamma,
        /*oxygen_ice_beta*/           polymorphs::oxygen_ice_gamma,
        /*oxygen_ice_alpha*/          polymorphs::oxygen_ice_gamma,
        /*carbon_dioxide_ice*/        polymorphs::carbon_dioxide_ice,
        /*methane_ice_alpha*/         polymorphs::methane_ice_alpha,
        /*methane_ice_beta*/          polymorphs::methane_ice_alpha,
        /*argon_ice*/                 polymorphs::argon_ice,
        /*helium_ice*/                polymorphs::helium_ice,
        /*hydrogen_ice*/              polymorphs::hydrogen_ice,
        /*ammonia_ice*/               polymorphs::ammonia_ice,
        /*ozone_ice*/                 polymorphs::ozone_ice,
        /*nitrous_oxide_ice*/         polymorphs::nitrous_oxide_ice,
        /*sulfur_dioxide_ice*/        polymorphs::sulfur_dioxide_ice,
        /*nitric_oxide_ice*/          polymorphs::nitric_oxide_ice,
        /*carbon_monoxide_ice_beta*/  polymorphs::carbon_monoxide_ice_beta,
        /*carbon_monoxide_ice_alpha*/ polymorphs::carbon_monoxide_ice_beta,
        /*ethane_ice*/                polymorphs::ethane_ice,
        /*hydrogen_cyanide_ice*/      polymorphs::hydrogen_cyanide_ice,
        /*ethanol_ice*/               polymorphs::ethanol_ice,
        /*formaldehyde_ice*/          polymorphs::formaldehyde_ice,
        /*formic_acid_ice*/           polymorphs::formic_acid_ice,
        /*perflouromethane_ice*/      polymorphs::perflouromethane_ice,
        /*benzene_ice*/               polymorphs::benzene_ice,
        /*pyrimidine_ice*/            polymorphs::pyrimidine_ice,
        /*quartz_alpha*/              polymorphs::quartz_alpha,
        /*quartz_beta*/               polymorphs::quartz_alpha,
        /*crystoballite_alpha*/       polymorphs::crystoballite_alpha,
        /*crystoballite_beta*/        polymorphs::crystoballite_alpha,
        /*halite*/                    polymorphs::halite,
        /*corundum*/                  polymorphs::corundum,
        /*apatite*/                   polymorphs::apatite,
        /*graphite*/                  polymorphs::graphite,
        /*diamond*/                   polymorphs::graphite,
        /*calcite*/                   polymorphs::calcite,
        /*aragonite*/                 polymorphs::calcite,
        /*orthoclase*/                polymorphs::orthoclase,
        /*andesine*/                  polymorphs::andesine,
        /*augite*/                    polymorphs::augite,
        /*forsterite*/                polymorphs::forsterite,
        /*goethite*/                  polymorphs::goethite,
        /*pyrite*/                    polymorphs::pyrite,
        /*hematite*/                  polymorphs::hematite,
        /*gold*/                      polymorphs::gold,
        /*silver*/                    polymorphs::silver,
        /*copper*/                    polymorphs::copper,
        /*magnetite*/                 polymorphs::magnetite,
        /*chalcocite_alpha*/          polymorphs::chalcocite_alpha,
        /*chalcocite_beta*/           polymorphs::chalcocite_alpha,
        /*chalcopyrite*/              polymorphs::chalcopyrite
    };

    table::FullTable<int> polymorph_compound_similarity {
        /*water_ice_1h*/              polymorphs::water_ice_1h,
        /*water_ice_1c*/              polymorphs::water_ice_1h,
        /*water_ice_2*/               polymorphs::water_ice_1h,
        /*water_ice_3*/               polymorphs::water_ice_1h,
        /*water_ice_4*/               polymorphs::water_ice_1h,
        /*water_ice_5*/               polymorphs::water_ice_1h,
        /*water_ice_6*/               polymorphs::water_ice_1h,
        /*water_ice_7*/               polymorphs::water_ice_1h,
        /*water_ice_8*/               polymorphs::water_ice_1h,
        /*water_ice_9*/               polymorphs::water_ice_1h,
        /*water_ice_10*/              polymorphs::water_ice_1h,
        /*water_ice_11h*/             polymorphs::water_ice_1h,
        /*water_ice_11o*/             polymorphs::water_ice_1h,
        /*water_ice_12*/              polymorphs::water_ice_1h,
        /*water_ice_13*/              polymorphs::water_ice_1h,
        /*water_ice_14*/              polymorphs::water_ice_1h,
        /*water_ice_15*/              polymorphs::water_ice_1h,
        /*water_ice_16*/              polymorphs::water_ice_1h,
        /*water_ice_17*/              polymorphs::water_ice_1h,
        /*water_ice_18*/              polymorphs::water_ice_1h,
        /*water_ice_19*/              polymorphs::water_ice_1h,
        /*nitrogen_ice_beta*/         polymorphs::water_ice_1h,
        /*nitrogen_ice_alpha*/        polymorphs::nitrogen_ice_beta,
        /*nitrogen_ice_gamma*/        polymorphs::nitrogen_ice_beta,
        /*oxygen_ice_gamma*/          polymorphs::nitrogen_ice_beta,
        /*oxygen_ice_beta*/           polymorphs::oxygen_ice_gamma,
        /*oxygen_ice_alpha*/          polymorphs::oxygen_ice_gamma,
        /*carbon_dioxide_ice*/        polymorphs::water_ice_1h,
        /*methane_ice_alpha*/         polymorphs::carbon_dioxide_ice,
        /*methane_ice_beta*/          polymorphs::methane_ice_alpha,
        /*argon_ice*/                 polymorphs::helium_ice,
        /*helium_ice*/                polymorphs::hydrogen_ice,
        /*hydrogen_ice*/              polymorphs::water_ice_1h,
        /*ammonia_ice*/               polymorphs::nitrogen_ice_beta,
        /*ozone_ice*/                 polymorphs::oxygen_ice_gamma,
        /*nitrous_oxide_ice*/         polymorphs::nitrogen_ice_beta,
        /*sulfur_dioxide_ice*/        polymorphs::nitrogen_ice_beta,
        /*nitric_oxide_ice*/          polymorphs::nitrogen_ice_beta,
        /*carbon_monoxide_ice_beta*/  polymorphs::carbon_dioxide_ice,
        /*carbon_monoxide_ice_alpha*/ polymorphs::carbon_monoxide_ice_beta,
        /*ethane_ice*/                polymorphs::methane_ice_alpha,
        /*hydrogen_cyanide_ice*/      polymorphs::carbon_dioxide_ice,
        /*ethanol_ice*/               polymorphs::ethane_ice,
        /*formaldehyde_ice*/          polymorphs::methane_ice_alpha,
        /*formic_acid_ice*/           polymorphs::formaldehyde_ice,
        /*perflouromethane_ice*/      polymorphs::methane_ice_alpha,
        /*benzene_ice*/               polymorphs::formaldehyde_ice,
        /*pyrimidine_ice*/            polymorphs::benzene_ice,
        /*quartz_alpha*/              polymorphs::halite,
        /*quartz_beta*/               polymorphs::quartz_alpha,
        /*crystoballite_alpha*/       polymorphs::quartz_alpha,
        /*crystoballite_beta*/        polymorphs::crystoballite_alpha,
        /*halite*/                    polymorphs::water_ice_1h,
        /*corundum*/                  polymorphs::quartz_alpha,
        /*apatite*/                   polymorphs::halite,
        /*graphite*/                  polymorphs::quartz_alpha,
        /*diamond*/                   polymorphs::graphite,
        /*calcite*/                   polymorphs::halite,
        /*aragonite*/                 polymorphs::calcite,
        /*orthoclase*/                polymorphs::quartz_alpha,
        /*andesine*/                  polymorphs::quartz_alpha,
        /*augite*/                    polymorphs::quartz_alpha,
        /*forsterite*/                polymorphs::quartz_alpha,
        /*goethite*/                  polymorphs::quartz_alpha,
        /*pyrite*/                    polymorphs::quartz_alpha,
        /*hematite*/                  polymorphs::quartz_alpha,
        /*gold*/                      polymorphs::copper,
        /*silver*/                    polymorphs::copper,
        /*copper*/                    polymorphs::chalcopyrite,
        /*magnetite*/                 polymorphs::quartz_alpha,
        /*chalcocite_alpha*/          polymorphs::pyrite,
        /*chalcocite_beta*/           polymorphs::chalcocite_alpha,
        /*chalcopyrite*/              polymorphs::pyrite
    };

    table::FullTable<int> canonical_polymorph {
        /*water*/            polymorphs::water_ice_1h,
        /*nitrogen*/         polymorphs::nitrogen_ice_beta,
        /*oxygen*/           polymorphs::oxygen_ice_gamma,
        /*carbon_dioxide*/   polymorphs::carbon_dioxide_ice,
        /*methane*/          polymorphs::methane_ice_alpha,
        /*argon*/            polymorphs::argon_ice,
        /*helium*/           polymorphs::helium_ice,
        /*hydrogen*/         polymorphs::hydrogen_ice,
        /*ammonia*/          polymorphs::ammonia_ice,
        /*ozone*/            polymorphs::ozone_ice,
        /*nitrous_oxide*/    polymorphs::nitrous_oxide_ice,
        /*sulfur_dioxide*/   polymorphs::sulfur_dioxide_ice,
        /*nitric_oxide*/     polymorphs::nitric_oxide_ice,
        /*carbon_monoxide*/  polymorphs::carbon_monoxide_ice_beta,
        /*ethane*/           polymorphs::ethane_ice,
        /*hydrogen_cyanide*/ polymorphs::hydrogen_cyanide_ice,
        /*ethanol*/          polymorphs::ethanol_ice,
        /*formaldehyde*/     polymorphs::formaldehyde_ice,
        /*formic_acid*/      polymorphs::formic_acid_ice,
        /*perflouromethane*/ polymorphs::perflouromethane_ice,
        /*benzene*/          polymorphs::benzene_ice,
        /*pyrimidine*/       polymorphs::pyrimidine_ice,
        /*quartz*/           polymorphs::quartz_alpha,
        /*halite*/           polymorphs::halite,
        /*corundum*/         polymorphs::corundum,
        /*apatite*/          polymorphs::apatite,
        /*carbon*/           polymorphs::graphite,
        /*calcite*/          polymorphs::calcite,
        /*orthoclase*/       polymorphs::orthoclase,
        /*andesine*/         polymorphs::andesine,
        /*augite*/           polymorphs::augite,
        /*forsterite*/       polymorphs::forsterite,
        /*goethite*/         polymorphs::goethite,
        /*pyrite*/           polymorphs::pyrite,
        /*hematite*/         polymorphs::hematite,
        /*gold*/             polymorphs::gold,
        /*silver*/           polymorphs::silver,
        /*copper*/           polymorphs::copper,
        /*magnetite*/        polymorphs::magnetite,
        /*chalcocite*/       polymorphs::chalcocite_alpha,
        /*chalcopyrite*/     polymorphs::chalcopyrite
    };

    table::FullTable<int> polymorph_compound {
        /*water_ice_1h*/              compounds::water,
        /*water_ice_1c*/              compounds::water,
        /*water_ice_2*/               compounds::water,
        /*water_ice_3*/               compounds::water,
        /*water_ice_4*/               compounds::water,
        /*water_ice_5*/               compounds::water,
        /*water_ice_6*/               compounds::water,
        /*water_ice_7*/               compounds::water,
        /*water_ice_8*/               compounds::water,
        /*water_ice_9*/               compounds::water,
        /*water_ice_10*/              compounds::water,
        /*water_ice_11h*/             compounds::water,
        /*water_ice_11o*/             compounds::water,
        /*water_ice_12*/              compounds::water,
        /*water_ice_13*/              compounds::water,
        /*water_ice_14*/              compounds::water,
        /*water_ice_15*/              compounds::water,
        /*water_ice_16*/              compounds::water,
        /*water_ice_17*/              compounds::water,
        /*water_ice_18*/              compounds::water,
        /*water_ice_19*/              compounds::water,
        /*nitrogen_ice_beta*/         compounds::nitrogen,
        /*nitrogen_ice_alpha*/        compounds::nitrogen,
        /*nitrogen_ice_gamma*/        compounds::nitrogen,
        /*oxygen_ice_gamma*/          compounds::oxygen,
        /*oxygen_ice_beta*/           compounds::oxygen,
        /*oxygen_ice_alpha*/          compounds::oxygen,
        /*carbon_dioxide_ice*/        compounds::carbon_dioxide,
        /*methane_ice_alpha*/         compounds::methane,
        /*methane_ice_beta*/          compounds::methane,
        /*argon_ice*/                 compounds::argon,
        /*helium_ice*/                compounds::helium,
        /*hydrogen_ice*/              compounds::hydrogen,
        /*ammonia_ice*/               compounds::ammonia,
        /*ozone_ice*/                 compounds::ozone,
        /*nitrous_oxide_ice*/         compounds::nitrous_oxide,
        /*sulfur_dioxide_ice*/        compounds::sulfur_dioxide,
        /*nitric_oxide_ice*/          compounds::nitric_oxide,
        /*carbon_monoxide_ice_beta*/  compounds::carbon_monoxide,
        /*carbon_monoxide_ice_alpha*/ compounds::carbon_monoxide,
        /*ethane_ice*/                compounds::ethane,
        /*hydrogen_cyanide_ice*/      compounds::hydrogen_cyanide,
        /*ethanol_ice*/               compounds::ethanol,
        /*formaldehyde_ice*/          compounds::formaldehyde,
        /*formic_acid_ice*/           compounds::formic_acid,
        /*perflouromethane_ice*/      compounds::perflouromethane,
        /*benzene_ice*/               compounds::benzene,
        /*pyrimidine_ice*/            compounds::pyrimidine,
        /*quartz_alpha*/              compounds::quartz,
        /*quartz_beta*/               compounds::quartz,
        /*crystoballite_alpha*/       compounds::quartz,
        /*crystoballite_beta*/        compounds::quartz,
        /*halite*/                    compounds::halite,
        /*corundum*/                  compounds::corundum,
        /*apatite*/                   compounds::apatite,
        /*graphite*/                  compounds::carbon,
        /*diamond*/                   compounds::carbon,
        /*calcite*/                   compounds::calcite,
        /*aragonite*/                 compounds::calcite,
        /*orthoclase*/                compounds::orthoclase,
        /*andesine*/                  compounds::andesine,
        /*augite*/                    compounds::augite,
        /*forsterite*/                compounds::forsterite,
        /*goethite*/                  compounds::goethite,
        /*pyrite*/                    compounds::pyrite,
        /*hematite*/                  compounds::hematite,
        /*gold*/                      compounds::gold,
        /*silver*/                    compounds::silver,
        /*copper*/                    compounds::copper,
        /*magnetite*/                 compounds::magnetite,
        /*chalcocite_alpha*/          compounds::chalcocite,
        /*chalcocite_beta*/           compounds::chalcocite,
        /*chalcopyrite*/              compounds::chalcopyrite
    };

}
