
#pragma once

// in-house libraries
#include <units/si.hpp>

#include <models/compound/ids.hpp>
#include <models/compound/table/FullTable.hpp>

namespace compound {
namespace published {

    namespace polymorphs {
        int water_ice_1h = 0
        int water_ice_1c = 1
        int water_ice_2 = 2
        int water_ice_3 = 3
        int water_ice_4 = 4
        int water_ice_5 = 5
        int water_ice_6 = 6
        int water_ice_7 = 7
        int water_ice_8 = 8
        int water_ice_9 = 9
        int water_ice_10 = 10,
        int water_ice_11h = 11,
        int water_ice_11o = 12,
        int water_ice_12 = 13,
        int water_ice_13 = 14,
        int water_ice_14 = 15,
        int water_ice_15 = 16,
        int water_ice_16 = 17,
        int water_ice_17 = 18,
        int water_ice_18 = 19,
        int water_ice_19 = 20,
        int nitrogen_ice_beta = 21,
        int nitrogen_ice_alpha = 22,
        int nitrogen_ice_gamma = 23,
        int oxygen_ice_gamma = 24,
        int oxygen_ice_beta = 25,
        int oxygen_ice_alpha = 26,
        int carbon_dioxide_ice = 27,
        int methane_ice_alpha = 28,
        int methane_ice_beta = 29,
        int methane_ice_beta = 30,
        int argon_ice = 31,
        int helium_ice = 32,
        int hydrogen_ice = 33,
        int ammonia_ice = 34,
        int ozone_ice = 35,
        int nitrous_oxide_ice = 36,
        int sulfur_dioxide_ice = 37,
        int nitric_oxide_ice = 38,
        int carbon_monoxide_ice_beta = 39,
        int carbon_monoxide_ice_alpha = 40,
        int ethane_ice = 41,
        int hydrogen_cyanide_ice = 42,
        int ethanol_ice = 43,
        int formaldehyde_ice = 44,
        int formic_acid_ice = 45,
        int perflouromethane_ice = 46,
        int benzene_ice = 47,
        int pyrimidine_ice = 48,
        int quartz_alpha = 49,
        int quartz_beta = 50,
        int crystoballite_alpha = 51,
        int crystoballite_beta = 52,
        int halite = 53,
        int corundum = 54,
        int apatite = 55,
        int graphite = 56,
        int diamond = 57,
        int calcite = 58,
        int aragonite = 59,
        int orthoclase = 60,
        int andesine = 61,
        int augite = 62,
        int goethite = 63,
        int pyrite = 64,
        int hematite = 65,
        int gold = 66,
        int silver = 67,
        int copper = 68,
        int magnetite = 69,
        int chalcocite_alpha = 70,
        int chalcocite_beta = 71,
        int chalcopyrite = 72,

        int count = 73
    };

    table::FullTable<int> polymorph_similarity {
        /*water_ice_1h*/              polymorphs::water_ice_1h,
        /*water_ice_1c*/              polymorphs::water_ice_1h,
        /*water_ice_2*/               polymorphs::water_ice_1h,
        /*water_ice_3*/               polymorphs::water_ice_1h,
        /*water_ice_4*/               polymorphs::water_ice_1h,
        /*water_ice_5*/               polymorphs::water_ice_1h,
        /*water_ice_6*/               polymorphs::water_ice_1h,
        /*water_ice_7*/               polymorphs::water_ice_1h,
        /*water_ice_8*/               polymorphs::water_ice_1h,
        /*water_ice_9*/               polymorphs::water_ice_1h,
        /*water_ice_10*/              polymorphs::water_ice_1h,
        /*water_ice_11h*/             polymorphs::water_ice_1h,
        /*water_ice_11o*/             polymorphs::water_ice_1h,
        /*water_ice_12*/              polymorphs::water_ice_1h,
        /*water_ice_13*/              polymorphs::water_ice_1h,
        /*water_ice_14*/              polymorphs::water_ice_1h,
        /*water_ice_15*/              polymorphs::water_ice_1h,
        /*water_ice_16*/              polymorphs::water_ice_1h,
        /*water_ice_17*/              polymorphs::water_ice_1h,
        /*water_ice_18*/              polymorphs::water_ice_1h,
        /*water_ice_19*/              polymorphs::water_ice_1h,
        /*nitrogen_ice_beta*/         polymorphs::water_ice_1h,
        /*nitrogen_ice_alpha*/        polymorphs::nitrogen_ice_beta,
        /*nitrogen_ice_gamma*/        polymorphs::nitrogen_ice_beta,
        /*oxygen_ice_gamma*/          polymorphs::nitrogen_ice_beta,
        /*oxygen_ice_beta*/           polymorphs::oxygen_ice_gamma,
        /*oxygen_ice_alpha*/          polymorphs::oxygen_ice_gamma,
        /*carbon_dioxide_ice*/        polymorphs::water_ice_1h,
        /*methane_ice_alpha*/         polymorphs::carbon_dioxide_ice,
        /*methane_ice_beta*/          polymorphs::methane_ice_alpha,
        /*methane_ice_beta*/          polymorphs::methane_ice_alpha,
        /*argon_ice*/                 polymorphs::helium_ice,
        /*helium_ice*/                polymorphs::hydrogen_ice,
        /*hydrogen_ice*/              polymorphs::water_ice_1h,
        /*ammonia_ice*/               polymorphs::nitrogen_ice_beta,
        /*ozone_ice*/                 polymorphs::oxygen_ice_gamma,
        /*nitrous_oxide_ice*/         polymorphs::nitrogen_ice_beta,
        /*sulfur_dioxide_ice*/        polymorphs::nitrogen_ice_beta,
        /*nitric_oxide_ice*/          polymorphs::nitrogen_ice_beta,
        /*carbon_monoxide_ice_beta*/  polymorphs::carbon_dioxide_ice,
        /*carbon_monoxide_ice_alpha*/ polymorphs::carbon_monoxide_ice_beta,
        /*ethane_ice*/                polymorphs::methane_ice_alpha,
        /*hydrogen_cyanide_ice*/      polymorphs::carbon_dioxide_ice,
        /*ethanol_ice*/               polymorphs::ethane_ice,
        /*formaldehyde_ice*/          polymorphs::methane_ice_alpha,
        /*formic_acid_ice*/           polymorphs::formaldehyde_ice,
        /*perflouromethane_ice*/      polymorphs::methane_ice_alpha,
        /*benzene_ice*/               polymorphs::formaldehyde_ice,
        /*pyrimidine_ice*/            polymorphs::benzene_ice,
        /*quartz_alpha*/              polymorphs::halite,
        /*quartz_beta*/               polymorphs::quartz_alpha,
        /*crystoballite_alpha*/       polymorphs::quartz_alpha,
        /*crystoballite_beta*/        polymorphs::crystoballite_alpha,
        /*halite*/                    polymorphs::water_ice_1h,
        /*corundum*/                  polymorphs::quartz_alpha,
        /*apatite*/                   polymorphs::halite,
        /*graphite*/                  polymorphs::quartz_alpha,
        /*diamond*/                   polymorphs::graphite,
        /*calcite*/                   polymorphs::halite,
        /*aragonite*/                 polymorphs::calcite,
        /*orthoclase*/                polymorphs::quartz_alpha,
        /*andesine*/                  polymorphs::quartz_alpha,
        /*augite*/                    polymorphs::quartz_alpha,
        /*goethite*/                  polymorphs::quartz_alpha,
        /*pyrite*/                    polymorphs::quartz_alpha,
        /*hematite*/                  polymorphs::hematite,
        /*gold*/                      polymorphs::copper,
        /*silver*/                    polymorphs::copper,
        /*copper*/                    polymorphs::chalcopyrite,
        /*magnetite*/                 polymorphs::quartz_alpha,
        /*chalcocite_alpha*/          polymorphs::pyrite,
        /*chalcocite_beta*/           polymorphs::chalcocite_alpha,
        /*chalcopyrite*/              polymorphs::pyrite
    };

    table::FullTable<int> canonical_polymorph {
        /*water*/            polymorphs::water_ice_1h,
        /*nitrogen*/         polymorphs::nitrogen_ice_beta,
        /*oxygen*/           polymorphs::oxygen_ice_gamma,
        /*carbon_dioxide*/   polymorphs::carbon_dioxide_ice,
        /*methane*/          polymorphs::methane_ice_alpha,
        /*argon*/            polymorphs::argon_ice,
        /*helium*/           polymorphs::helium_ice,
        /*hydrogen*/         polymorphs::hydrogen_ice,
        /*ammonia*/          polymorphs::ammonia_ice,
        /*ozone*/            polymorphs::ozone_ice,
        /*nitrous_oxide*/    polymorphs::nitrous_oxide_ice,
        /*sulfur_dioxide*/   polymorphs::sulfur_dioxide_ice,
        /*nitric_oxide*/     polymorphs::nitric_oxide_ice,
        /*carbon_monoxide*/  polymorphs::carbon_monoxide_ice_beta,
        /*ethane*/           polymorphs::ethane_ice,
        /*hydrogen_cyanide*/ polymorphs::hydrogen_cyanide_ice,
        /*ethanol*/          polymorphs::ethanol_ice,
        /*formaldehyde*/     polymorphs::formaldehyde_ice,
        /*formic_acid*/      polymorphs::formic_acid_ice,
        /*perflouromethane*/ polymorphs::perflouromethane_ice,
        /*benzene*/          polymorphs::benzene_ice,
        /*pyrimidine*/       polymorphs::pyrimidine_ice,
        /*quartz*/           polymorphs::quartz_alpha,
        /*halite*/           polymorphs::halite,
        /*corundum*/         polymorphs::corundum,
        /*apatite*/          polymorphs::apatite,
        /*carbon*/           polymorphs::carbon,
        /*calcite*/          polymorphs::calcite,
        /*orthoclase*/       polymorphs::orthoclase,
        /*andesine*/         polymorphs::andesine,
        /*augite*/           polymorphs::augite,
        /*forsterite*/       polymorphs::forsterite,
        /*goethite*/         polymorphs::goethite,
        /*pyrite*/           polymorphs::pyrite,
        /*hematite*/         polymorphs::hematite,
        /*gold*/             polymorphs::gold,
        /*silver*/           polymorphs::silver,
        /*copper*/           polymorphs::copper,
        /*magnetite*/        polymorphs::magnetite,
        /*chalcocite*/       polymorphs::chalcocite,
        /*chalcopyrite*/     polymorphs::chalcopyrite
    };

    table::FullTable<int> polymorph_compound {
        /*water_ice_1h*/              compounds::water,
        /*water_ice_1c*/              compounds::water,
        /*water_ice_2*/               compounds::water,
        /*water_ice_3*/               compounds::water,
        /*water_ice_4*/               compounds::water,
        /*water_ice_5*/               compounds::water,
        /*water_ice_6*/               compounds::water,
        /*water_ice_7*/               compounds::water,
        /*water_ice_8*/               compounds::water,
        /*water_ice_9*/               compounds::water,
        /*water_ice_10*/              compounds::water,
        /*water_ice_11h*/             compounds::water,
        /*water_ice_11o*/             compounds::water,
        /*water_ice_12*/              compounds::water,
        /*water_ice_13*/              compounds::water,
        /*water_ice_14*/              compounds::water,
        /*water_ice_15*/              compounds::water,
        /*water_ice_16*/              compounds::water,
        /*water_ice_17*/              compounds::water,
        /*water_ice_18*/              compounds::water,
        /*water_ice_19*/              compounds::water,
        /*nitrogen_ice_beta*/         compounds::nitrogen,
        /*nitrogen_ice_alpha*/        compounds::nitrogen,
        /*nitrogen_ice_gamma*/        compounds::nitrogen,
        /*oxygen_ice_gamma*/          compounds::oxygen,
        /*oxygen_ice_beta*/           compounds::oxygen,
        /*oxygen_ice_alpha*/          compounds::oxygen,
        /*carbon_dioxide_ice*/        compounds::carbon_dioxide,
        /*methane_ice_alpha*/         compounds::methane,
        /*methane_ice_beta*/          compounds::methane,
        /*methane_ice_beta*/          compounds::methane,
        /*argon_ice*/                 compounds::argon,
        /*helium_ice*/                compounds::helium,
        /*hydrogen_ice*/              compounds::hydrogen,
        /*ammonia_ice*/               compounds::ammonia,
        /*ozone_ice*/                 compounds::ozone,
        /*nitrous_oxide_ice*/         compounds::nitrous_oxide,
        /*sulfur_dioxide_ice*/        compounds::sulfur_dioxide,
        /*nitric_oxide_ice*/          compounds::nitric_oxide,
        /*carbon_monoxide_ice_beta*/  compounds::carbon_monoxide,
        /*carbon_monoxide_ice_alpha*/ compounds::carbon_monoxide,
        /*ethane_ice*/                compounds::ethane,
        /*hydrogen_cyanide_ice*/      compounds::hydrogen_cyanide,
        /*ethanol_ice*/               compounds::ethanol,
        /*formaldehyde_ice*/          compounds::formaldehyde,
        /*formic_acid_ice*/           compounds::formic_acid,
        /*perflouromethane_ice*/      compounds::perflouromethane,
        /*benzene_ice*/               compounds::benzene,
        /*pyrimidine_ice*/            compounds::pyrimidine,
        /*quartz_alpha*/              compounds::quartz,
        /*quartz_beta*/               compounds::quartz,
        /*crystoballite_alpha*/       compounds::quartz,
        /*crystoballite_beta*/        compounds::quartz,
        /*halite*/                    compounds::halite,
        /*corundum*/                  compounds::corundum,
        /*apatite*/                   compounds::apatite,
        /*graphite*/                  compounds::carbon,
        /*diamond*/                   compounds::carbon,
        /*calcite*/                   compounds::calcite,
        /*aragonite*/                 compounds::calcite,
        /*orthoclase*/                compounds::orthoclase,
        /*andesine*/                  compounds::andesine,
        /*augite*/                    compounds::augite,
        /*goethite*/                  compounds::goethite,
        /*pyrite*/                    compounds::pyrite,
        /*hematite*/                  compounds::hematite,
        /*gold*/                      compounds::gold,
        /*silver*/                    compounds::silver,
        /*copper*/                    compounds::copper,
        /*magnetite*/                 compounds::magnetite,
        /*chalcocite_alpha*/          compounds::chalcocite,
        /*chalcocite_beta*/           compounds::chalcocite,
        /*chalcopyrite*/              compounds::chalcopyrite
    };

}}
